services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cafe-web
    networks:
      public:
      internal:
    ports:
      - "80:80"
    external_links:
      - "cafe_server-django:cafe_server-django"